"""Signal dataclasses for scalping strategies."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, Any


class SignalDirection(Enum):
    """Trade direction."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class ScalpSignal:
    """Signal generated by a scalping strategy.
    
    Attributes:
        direction: Trade direction (BUY/SELL/HOLD)
        symbol: Trading symbol (e.g., 'EURUSD')
        strategy_name: Name of the strategy that generated this signal
        entry_price: Recommended entry price
        sl_pips: Stop loss in pips
        tp_pips: Take profit in pips
        confidence: Signal confidence (0.0 - 1.0)
        reason: Human-readable reason for the signal
        metadata: Strategy-specific data (order blocks, FVG levels, etc.)
    """
    direction: SignalDirection
    symbol: str
    strategy_name: str
    entry_price: float
    sl_pips: float
    tp_pips: float
    confidence: float  # 0.0 - 1.0
    reason: str
    metadata: Dict[str, Any] = field(default_factory=dict)
