# Generated by Django 4.2.20 on 2026-09-05 12:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20)),
                ('analyst_type', models.CharField(max_length=50)),
                ('signal', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('reasoning', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analyst_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsensusResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20)),
                ('consensus_signal', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst_results', models.ManyToManyField(related_name='consensus_groups', to='django_app.analystresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensus_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consensus_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'db_table': 'users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consensus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_app.consensusresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('avg_entry_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='LegendaryModuleResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20)),
                ('module_name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('recommendation', models.CharField(max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legendary_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legendary_module_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
