# Generated by Django 4.2.20 on 2026-09-06 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='broker_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='fill_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='filled_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop'), ('STOP_LIMIT', 'Stop Limit')], default='MARKET', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='slippage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trailing_stop',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('PARTIAL', 'Partial'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop'), ('STOP_LIMIT', 'Stop Limit')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('PARTIAL', 'Partial'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('broker_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('filled_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('fill_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='django_app.trade')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broker', models.CharField(choices=[('MT4', 'MetaTrader 4'), ('MT5', 'MetaTrader 5')], default='MT5', max_length=4)),
                ('account_type', models.CharField(blank=True, choices=[('CENT', 'Cent'), ('STANDARD', 'Standard')], max_length=8, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('balance', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('equity', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('margin', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('free_margin', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('leverage', models.IntegerField(default=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_connected', models.BooleanField(default=False)),
                ('simulation_mode', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_configs',
            },
        ),
    ]
